// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 5.4
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
wowReInitor(jQuery("#wowslider-container1"),{effect:"dribbles",prev:"<i class='fa fa-arrow-left'></i>",next:"<i class='fa fa-arrow-right'></i>",duration:20*100,delay:40*100,width:740,height:360,autoPlay:true,playPause:false,stopOnHover:false,loop:false,bullets:0,caption:true,captionEffect:"slide",controls:true,onBeforeStep:0,images:0});